M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date lun 10 ott 2022, 21:45:52
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-10T21:45:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X5.7169Y-4.7131
X5.9445Y-4.7131
T0
M30
